#!/usr/bin/env node
/**
 * Renders profile/generated/PROFILE.md: a human review surface for a persona's
 * generated profile. Regenerate it; never hand-edit it.
 */
import fs from "node:fs";
import path from "node:path";

const SOURCE_TIERS = [
  { match: /evidence\/repositories\//, tier: "machine-retrievable", note: "tool snapshot of a repository" },
  { match: /performance-review|evidence\/performance-reviews\//, tier: "attested", note: "employer performance review" },
  { match: /profile\/background\.md$/, tier: "self-reported", note: "written by the persona" },
];

function tierFor(sourcePath) {
  const hit = SOURCE_TIERS.find((entry) => entry.match.test(sourcePath));
  return hit ? hit.tier : "other";
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function shortSource(source) {
  const name = source.path.split("/").slice(-1)[0];
  const lines = source.lineStart ? `:${source.lineStart}-${source.lineEnd}` : "";
  return `${name}${lines}`;
}

function renderClaim(claim) {
  const source = claim.sources[0];
  const where = source ? ` \`${shortSource(source)}\`` : " _(no source)_";
  const flag = claim.status === "verified" ? "" : ` **[${claim.status}]**`;
  return `  - \`${claim.id}\`${flag} — ${claim.fact}${where}`;
}

function renderUnit(unit, claimsById) {
  const lines = [];
  const dates = unit.ongoing ? `${unit.startDate}–present` : `${unit.startDate}–${unit.endDate || "?"}`;
  lines.push(`#### ${unit.externalTitle || unit.title}`);
  lines.push("");
  lines.push(
    `\`${unit.id}\` · ${unit.kind} · ${dates} · **${unit.evidenceStrength.tier}** evidence · ` +
      `${unit.contribution.replace(/_/g, " ")} · disclosure: ${unit.disclosure}`,
  );
  lines.push("");

  if (unit.scope?.surface) lines.push(`Surface: ${unit.scope.surface}`);
  if (unit.scope?.audience) lines.push(`Audience: ${unit.scope.audience}`);
  if (unit.scope?.productionExposure) lines.push(`Exposure: ${unit.scope.productionExposure}`);
  if (unit.techStack?.length) lines.push(`Stack: ${unit.techStack.join(", ")}`);
  lines.push("");

  if (unit.outcomes?.length) {
    lines.push("Outcomes:");
    for (const outcome of unit.outcomes) {
      lines.push(`  - ${outcome.metric} ${outcome.direction} — _${outcome.confidence}_ (\`${outcome.claimId}\`)`);
    }
    lines.push("");
  }

  // Limitations are the honest caveats a reviewer most needs; never omit them.
  if (unit.evidenceStrength.limitations?.length) {
    lines.push("Limitations:");
    for (const limitation of unit.evidenceStrength.limitations) lines.push(`  - ${limitation}`);
    lines.push("");
  }

  lines.push(`Claims (${unit.claimIds.length}):`);
  for (const id of unit.claimIds) {
    const claim = claimsById.get(id);
    lines.push(claim ? renderClaim(claim) : `  - \`${id}\` **[MISSING FROM LEDGER]**`);
  }
  lines.push("");
  return lines;
}

function renderIdentitySection(title, records, format) {
  if (!records?.length) return [];
  const lines = [`### ${title} (${records.length})`, ""];
  for (const record of records) lines.push(`- ${format(record)}`);
  lines.push("");
  return lines;
}

export function renderProfile(personaName, generatedDir) {
  const identity = readJson(path.join(generatedDir, "identity.json"));
  const ledger = readJson(path.join(generatedDir, "claims.json"));
  const bank = readJson(path.join(generatedDir, "accomplishments.json"));

  const claimsById = new Map(ledger.claims.map((claim) => [claim.id, claim]));
  const claimedByUnit = new Set(bank.units.flatMap((unit) => unit.claimIds));

  const tierCounts = {};
  for (const claim of ledger.claims) {
    const tier = claim.sources[0] ? tierFor(claim.sources[0].path) : "other";
    tierCounts[tier] = (tierCounts[tier] || 0) + 1;
  }

  const out = [];
  out.push(`# Profile review — ${personaName}`);
  out.push("");
  out.push(
    "_Generated by `src/tools/render-profile.js`. **Never hand-edit this file** — it is a view " +
      "of `identity.json`, `claims.json` and `accomplishments.json`, and an edit here changes " +
      "nothing the pipeline reads. Fix the source evidence and rebuild._",
  );
  out.push("");
  out.push(`Generated: ${new Date().toISOString()}`);
  out.push("");

  out.push("## At a glance");
  out.push("");
  out.push("| | Count |");
  out.push("|---|---|");
  out.push(`| Claims | ${ledger.claims.length} |`);
  out.push(`| Accomplishment units | ${bank.units.length} |`);
  out.push(`| Claims reachable by ranking | ${claimedByUnit.size} |`);
  out.push(`| Roles | ${identity.experience.length + (identity.other_experience_compacted?.length || 0)} |`);
  out.push(`| Education | ${identity.education?.length || 0} |`);
  out.push(`| Projects | ${identity.projects?.length || 0} |`);
  out.push(`| Certifications | ${identity.certifications?.length || 0} |`);
  out.push(`| Awards / contributions | ${identity.awards_or_contributions?.length || 0} |`);
  out.push("");

  out.push("## Can a stranger verify this?");
  out.push("");
  out.push("The single most useful review question. Claims grouped by what backs them:");
  out.push("");
  out.push("| Backing | Claims | What it means to a recruiter |");
  out.push("|---|---|---|");
  const tierMeaning = {
    "machine-retrievable": "a tool read it from a repository — checkable if the repo is public",
    attested: "an employer wrote it — real, but not visible outside the company",
    "self-reported": "the persona wrote it — weakest tier, treat as a lead",
    other: "uncategorised source — worth a look",
  };
  for (const [tier, count] of Object.entries(tierCounts).sort((a, b) => b[1] - a[1])) {
    out.push(`| ${tier} | ${count} | ${tierMeaning[tier] || ""} |`);
  }
  out.push("");

  const publicLinks = [
    ...(identity.projects || []).filter((p) => p.link).map((p) => `${p.name} — ${p.link}`),
    ...(identity.certifications || []).filter((c) => c.credential_url).map((c) => `${c.name} — ${c.credential_url}`),
    ...(identity.awards_or_contributions || []).filter((a) => a.link).map((a) => `${a.title} — ${a.link}`),
  ];
  out.push(`**Publicly linked records (${publicLinks.length})** — these a stranger can open right now:`);
  out.push("");
  for (const link of publicLinks) out.push(`- ${link}`);
  out.push("");

  out.push("## Experience");
  out.push("");
  const allRoles = [...identity.experience, ...(identity.other_experience_compacted || [])];
  for (const role of allRoles) {
    out.push(`### ${role.company} — ${role.role} (${role.period})`);
    out.push("");
    for (const step of role.progression || []) {
      out.push(
        `- ${step.date}: **${step.label}** → renders externally as "${step.externalLabel}" ` +
          `(${step.disclosure})`,
      );
    }
    if (role.progression?.length) out.push("");

    const units = bank.units.filter((unit) => unit.experienceId === role.id);
    if (!units.length) {
      out.push("_No accomplishment units. This role renders from identity only._");
      out.push("");
      continue;
    }
    for (const unit of units.sort((a, b) => String(b.startDate).localeCompare(String(a.startDate)))) {
      out.push(...renderUnit(unit, claimsById));
    }
  }

  out.push("## Structural records");
  out.push("");
  out.push("_These render from identity sections and are not expected to have units._");
  out.push("");
  out.push(
    ...renderIdentitySection("Education", identity.education, (e) =>
      `${e.degree}, ${e.school} (${e.startDate}–${e.endDate})`),
  );
  out.push(
    ...renderIdentitySection("Projects", identity.projects, (p) =>
      `**${p.name}**${p.link ? ` — ${p.link}` : ""}`),
  );
  out.push(
    ...renderIdentitySection("Certifications", identity.certifications, (c) =>
      `${c.name} — ${c.issuer} ${c.year}${c.credential_url ? ` — ${c.credential_url}` : " — _no credential link_"}`),
  );
  out.push(
    ...renderIdentitySection("Awards & contributions", identity.awards_or_contributions, (a) =>
      `${a.title} (${a.year})${a.link ? ` — ${a.link}` : ""}`),
  );

  const orphans = ledger.claims.filter((claim) => !claimedByUnit.has(claim.id));
  out.push(`## Claims outside the accomplishment bank (${orphans.length})`);
  out.push("");
  out.push(
    "_Not a defect on its own — roles, education, certifications and awards render from " +
      "identity sections. Worth scanning for work that should be rankable but is not._",
  );
  out.push("");
  for (const claim of orphans) out.push(renderClaim(claim));
  out.push("");

  return out.join("\n");
}

function main() {
  const personaName = process.argv[2];
  if (!personaName) {
    console.error("usage: labora render-profile <persona-name>");
    process.exit(2);
  }
  const generatedDir = path.join("data/personas", personaName, "profile/generated");
  if (!fs.existsSync(generatedDir)) {
    console.error(`No generated profile at ${generatedDir}`);
    process.exit(2);
  }
  const target = path.join(generatedDir, "PROFILE.md");
  fs.writeFileSync(target, renderProfile(personaName, generatedDir));
  console.log(`wrote ${target}`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
