#!/usr/bin/env node
/**
 * Renders profile/generated/PROFILE.md: a human review surface for a persona's
 * generated profile. Regenerate it; never hand-edit it.
 */
import fs from "node:fs";
import path from "node:path";

import { resolvePersonaRoot } from "../lib/workspace.js";
import { loadManifest, resolveProvenance, SOURCE_KIND_MEANING } from "../lib/evidence-provenance.js";


function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function shortSource(source) {
  const name = source.path.split("/").slice(-1)[0];
  const lines = source.lineStart ? `:${source.lineStart}-${source.lineEnd}` : "";
  return `${name}${lines}`;
}

function disclosureLabel(disclosure) {
  return disclosure || "**unclassified**";
}

function renderClaim(claim) {
  const source = claim.sources[0];
  const where = source ? ` \`${shortSource(source)}\`` : " _(no source)_";
  const flag = claim.status === "verified" ? "" : ` **[${claim.status}]**`;
  return `  - \`${claim.id}\`${flag} · disclosure: ${disclosureLabel(claim.disclosure)} — ${claim.fact}${where}`;
}

function renderUnit(unit, claimsById) {
  const lines = [];
  const dates = unit.ongoing ? `${unit.startDate}–present` : `${unit.startDate}–${unit.endDate || "?"}`;
  lines.push(`#### ${unit.externalTitle || unit.title}`);
  lines.push("");
  lines.push(
    `\`${unit.id}\` · ${unit.kind} · ${dates} · **${unit.evidenceStrength.tier}** evidence · ` +
      `${unit.contribution.replace(/_/g, " ")} · disclosure: ${unit.disclosure}`,
  );
  lines.push("");

  if (unit.scope?.surface) lines.push(`Surface: ${unit.scope.surface}`);
  if (unit.scope?.audience) lines.push(`Audience: ${unit.scope.audience}`);
  if (unit.scope?.productionExposure) lines.push(`Exposure: ${unit.scope.productionExposure}`);
  if (unit.techStack?.length) lines.push(`Stack: ${unit.techStack.join(", ")}`);
  lines.push("");

  if (unit.outcomes?.length) {
    lines.push("Outcomes:");
    for (const outcome of unit.outcomes) {
      lines.push(`  - ${outcome.metric} ${outcome.direction} — _${outcome.confidence}_ (\`${outcome.claimId}\`)`);
    }
    lines.push("");
  }

  // Limitations are the honest caveats a reviewer most needs; never omit them.
  if (unit.evidenceStrength.limitations?.length) {
    lines.push("Limitations:");
    for (const limitation of unit.evidenceStrength.limitations) lines.push(`  - ${limitation}`);
    lines.push("");
  }

  lines.push(`Claims (${unit.claimIds.length}):`);
  for (const id of unit.claimIds) {
    const claim = claimsById.get(id);
    lines.push(claim ? renderClaim(claim) : `  - \`${id}\` **[MISSING FROM LEDGER]**`);
  }
  lines.push("");
  return lines;
}

function renderIdentitySection(title, records, format) {
  if (!records?.length) return [];
  const lines = [`### ${title} (${records.length})`, ""];
  for (const record of records) lines.push(`- ${format(record)}`);
  lines.push("");
  return lines;
}

export function renderProfile(personaName, generatedDir, personaRoot = null) {
  const identity = readJson(path.join(generatedDir, "identity.json"));
  const ledger = readJson(path.join(generatedDir, "claims.json"));
  const bank = readJson(path.join(generatedDir, "accomplishments.json"));

  const claimsById = new Map(ledger.claims.map((claim) => [claim.id, claim]));
  const claimedByUnit = new Set(bank.units.flatMap((unit) => unit.claimIds));

  // Every source, not `sources[0]`. A claim backed by a candidate statement and
  // an employer document cannot honestly be reduced to whichever happens to be
  // first, and picking one silently chooses a story about the evidence.
  const manifest = personaRoot
    ? loadManifest(personaRoot)
    : { present: false, sources: new Map(), issues: [] };
  const kindCounts = {};
  const undeclaredSources = new Map();
  const staleSources = new Map();
  const seen = new Set();
  for (const claim of ledger.claims) {
    for (const source of claim.sources) {
      const resolved = personaRoot
        ? resolveProvenance(source.path, personaRoot, manifest)
        : { state: "undeclared", relative: source.path, sourceKind: null };
      if (resolved.state === "undeclared") {
        undeclaredSources.set(resolved.relative, (undeclaredSources.get(resolved.relative) || 0) + 1);
      } else if (resolved.state === "stale") {
        staleSources.set(resolved.relative, (staleSources.get(resolved.relative) || 0) + 1);
      }
      const key = `${claim.id}::${resolved.sourceKind || "undeclared"}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const bucket = resolved.sourceKind || "undeclared";
      kindCounts[bucket] = (kindCounts[bucket] || 0) + 1;
    }
  }

  const out = [];
  out.push(`# Profile review — ${personaName}`);
  out.push("");
  out.push(
    "_Generated by `src/tools/render-profile.js`. **Never hand-edit this file** — it is a view " +
      "of `identity.json`, `claims.json` and `accomplishments.json`, and an edit here changes " +
      "nothing the pipeline reads. Fix the source evidence and rebuild._",
  );
  out.push("");
  out.push(`Generated: ${new Date().toISOString()}`);
  out.push("");

  out.push("## At a glance");
  out.push("");
  out.push("| | Count |");
  out.push("|---|---|");
  out.push(`| Claims | ${ledger.claims.length} |`);
  out.push(`| Accomplishment units | ${bank.units.length} |`);
  out.push(`| Claims reachable by ranking | ${claimedByUnit.size} |`);
  out.push(`| Roles | ${identity.experience.length + (identity.other_experience_compacted?.length || 0)} |`);
  out.push(`| Education | ${identity.education?.length || 0} |`);
  out.push(`| Projects | ${identity.projects?.length || 0} |`);
  out.push(`| Certifications | ${identity.certifications?.length || 0} |`);
  out.push(`| Awards / contributions | ${identity.awards_or_contributions?.length || 0} |`);
  out.push("");

  out.push("## What backs each claim?");
  out.push("");
  out.push(
    "Grouped by **what kind of source** supports it. This is not a strength ranking "
    + "and nothing downstream scores or sorts by it — it is here so you know how to "
    + "talk about each fact, not whether to trust it."
  );
  out.push("");
  out.push("| Source kind | Claims | What it means when you are asked about it |");
  out.push("|---|---|---|");
  for (const [kind, count] of Object.entries(kindCounts).sort((a, b) => b[1] - a[1])) {
    const meaning = kind === "undeclared"
      ? "Provenance not yet declared in `evidence/PROVENANCE.json`. Claim grounding is unaffected."
      : (SOURCE_KIND_MEANING[kind] || "");
    out.push(`| ${kind} | ${count} | ${meaning} |`);
  }
  out.push("");
  out.push(
    "> **Restricted access is not a weak source.** Most real production work sits behind "
    + "a login, a private repository or an NDA. That changes how you demonstrate it — a demo, "
    + "a walkthrough, a description of the design — never whether it counts."
  );
  out.push("");

  // Two separate statements, deliberately. Claim integrity is a hard property
  // that either holds or does not. Provenance coverage is metadata debt. Merging
  // them into one table is how "an employer wrote it" got attached to 62 claims
  // nobody had ever said that about.
  if (undeclaredSources.size || staleSources.size || manifest.issues.length) {
    out.push("### Provenance metadata");
    out.push("");
    out.push("_Claim grounding is validated separately by `labora validate-profile` and is not affected by anything in this section._");
    out.push("");
    for (const issue of manifest.issues) {
      out.push(`- **${issue.code}** — ${issue.message}`);
    }
    if (staleSources.size) {
      out.push(`- **Stale entries (${staleSources.size} sources).** The manifest classifies different bytes than are on disk, so the classification is not current. Re-run \`profile-builder\` after updating \`evidence/PROVENANCE.json\`:`);
      for (const [file, count] of [...staleSources].sort((a, b) => b[1] - a[1])) {
        out.push(`  - \`${file}\` — ${count} claim references`);
      }
    }
    if (undeclaredSources.size) {
      out.push(`- **Undeclared (${undeclaredSources.size} sources).** Add an entry to \`evidence/PROVENANCE.json\` for each, then re-run \`profile-builder\`. Ranked by how many claims are affected:`);
      for (const [file, count] of [...undeclaredSources].sort((a, b) => b[1] - a[1])) {
        out.push(`  - \`${file}\` — ${count} claim references`);
      }
    }
    out.push("");
  }

  const publicLinks = [
    ...(identity.projects || []).filter((p) => p.link).map((p) => `${p.name} — ${p.link}`),
    ...(identity.certifications || []).filter((c) => c.credential_url).map((c) => `${c.name} — ${c.credential_url}`),
    ...(identity.awards_or_contributions || []).filter((a) => a.link).map((a) => `${a.title} — ${a.link}`),
  ];
  out.push(`**Publicly linked records (${publicLinks.length})** — these a stranger can open right now:`);
  out.push("");
  for (const link of publicLinks) out.push(`- ${link}`);
  out.push("");

  out.push("## Experience");
  out.push("");
  const allRoles = [...identity.experience, ...(identity.other_experience_compacted || [])];
  for (const role of allRoles) {
    out.push(`### ${role.company} — ${role.role} (${role.period})`);
    out.push("");
    for (const step of role.progression || []) {
      out.push(
        `- ${step.date}: **${step.label}** → renders externally as "${step.externalLabel}" ` +
          `(${disclosureLabel(step.disclosure)})`,
      );
    }
    if (role.progression?.length) out.push("");

    const units = bank.units.filter((unit) => unit.experienceId === role.id);
    if (!units.length) {
      out.push("_No accomplishment units. This role renders from identity only._");
      out.push("");
      continue;
    }
    for (const unit of units.sort((a, b) => String(b.startDate).localeCompare(String(a.startDate)))) {
      out.push(...renderUnit(unit, claimsById));
    }
  }

  out.push("## Structural records");
  out.push("");
  out.push("_These render from identity sections and are not expected to have units._");
  out.push("");
  out.push(
    ...renderIdentitySection("Education", identity.education, (e) =>
      `${e.degree}, ${e.school} (${e.startDate}–${e.endDate})`),
  );
  // Descriptions and highlights are the only prose the identity record renders,
  // so they are the only part a reviewer can catch drifting from evidence.
  // Showing them beside the claims that ground them makes that check possible;
  // rendering the name alone leaves the prose unreviewed as well as unverified.
  const renderProse = (record) => {
    const lines = [];
    const description = String(record.description || "").trim();
    if (description) lines.push(`  - ${description}`);
    for (const highlight of record.highlights || []) {
      const text = String(highlight || "").trim();
      if (text) lines.push(`  - ${text}`);
    }
    if (lines.length) {
      const ids = record.claimIds || [];
      lines.push(`  - _grounded by:_ ${ids.length ? ids.join(", ") : "**nothing**"}`);
    }
    return lines.join("\n");
  };

  out.push(
    ...renderIdentitySection("Projects", identity.projects, (p) => {
      const prose = renderProse(p);
      return `**${p.name}**${p.link ? ` — ${p.link}` : ""}${prose ? `\n${prose}` : ""}`;
    }),
  );
  out.push(
    ...renderIdentitySection("Certifications", identity.certifications, (c) =>
      `${c.name} — ${c.issuer} ${c.year}${c.credential_url ? ` — ${c.credential_url}` : " — _no credential link_"}`),
  );
  out.push(
    ...renderIdentitySection("Awards & contributions", identity.awards_or_contributions, (a) => {
      const prose = renderProse(a);
      return `${a.title} (${a.year})${a.link ? ` — ${a.link}` : ""}${prose ? `\n${prose}` : ""}`;
    }),
  );

  const orphans = ledger.claims.filter((claim) => !claimedByUnit.has(claim.id));
  out.push(`## Claims outside the accomplishment bank (${orphans.length})`);
  out.push("");
  out.push(
    "_Not a defect on its own — roles, education, certifications and awards render from " +
      "identity sections. Worth scanning for work that should be rankable but is not._",
  );
  out.push("");
  for (const claim of orphans) out.push(renderClaim(claim));
  out.push("");

  return out.join("\n");
}

function main() {
  const personaArg = process.argv[2];
  if (!personaArg) {
    console.error("usage: labora render-profile <persona-name>");
    process.exit(2);
  }
  // Resolve through the shared persona search path. A relative "data/personas"
  // only resolves when the process runs from the plugin root against bundled
  // fixture data, which stopped being the normal case when persona data moved
  // to a separate private workspace.
  const personaRoot = fs.existsSync(personaArg) ? personaArg : resolvePersonaRoot(personaArg);
  const personaName = path.basename(personaRoot);
  const generatedDir = path.join(personaRoot, "profile/generated");
  if (!fs.existsSync(generatedDir)) {
    console.error(`No generated profile at ${generatedDir}`);
    process.exit(2);
  }
  const target = path.join(generatedDir, "PROFILE.md");
  fs.writeFileSync(target, renderProfile(personaName, generatedDir, personaRoot));
  console.log(`wrote ${target}`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
